#http端口
server:
  port: 8883
constant:
  #处理消息的线程数
  handleMsgTaskThreadNum: 3
  #自动创建房间检测间隔(单位:秒)
  createRoomInterval: 30
  #连接游戏服的地址
  activityServerAddr: "http://192.169.1.31:10513"
  #创建房间的url
  creatrRoomUrl: "http://192.169.1.31:10513/data?cmd=500&mAccId=%s&option=%s&mjType=%s&roomType=%s"
  #查询房间还有多少空位
  queryRoomSeatUrl: "http://192.169.1.31:10513/data?cmd=501&roomId=%s"
  #查询房间结算信息
  queryRoomSettlementUrl: "http://192.169.1.31:10513/data?cmd=502&roomId=%s"